### ISSUE TITLE
Inaccurate chapter title: VCL Built-in Subroutines

### ISSUE THREAD

**Issue by franciscovg** [varnish/Varnish-Book#108]
The title of Chapter 8 https://github.com/varnish/Varnish-Book/blob/master/varnish_book.rst#vcl-built-in-subroutines is inaccurate and somehow misleading. The title reads `VCL Built-in Subroutines`, which suggests the explanation of the details of the logic in the built-in subroutines. However, the chapter explains the purpose of each state (in the Varnish FSM) and gives examples about custom policies that are typically added.

Therefore I suggest to change the chapter title to one of the following (sorted by preference):

- Transactions Workflow in VCL
- Transactions Workflow in the Varnish State Machine

Thanks to @huayra for reporting this inaccuracy.

**Comment by franciscovg** [comment]
No opinions here?

**Comment by Dridi** [comment]
In the Varnish 3 course, the title was inaccurately "VCL functions" and covered the remaining subroutines (besides the two covered in VCL basics). In both VCL chapters we comment the built-in subroutines, except `vcl_init` and `vcl_fini`.

In the current course, we cover the state machines in the VCL Basics chapter. In the chapter subject to title changes we do cover the remaining subroutines (except purge that wasn't there in v3) and we still comment the built-in VCL for each subroutine.

So if I were to change this chapter title, I'd go with "VCL Subroutines" because that's what it covers, including their role in the FSMs and the built-in rules. Let's keep it *simple*.

**Comment by franciscovg** [comment]
Ok, I agree with renaming the title to ``VCL Subroutines``. If no one else has strong opinions, I'll proceed with this new title.

**Comment by franciscovg** [comment]
Changed in c97e6ff
