### ISSUE TITLE
Needs more coverage of varnishtop

### ISSUE THREAD

**Issue by mhagander** [varnish/Varnish-Book#36]
Right now, varnishtop is only covered in the appendix. Such a useful tool really should be covered earlier in the book, and in more detail.

**Comment by Dridi** [comment]
Hi,

My two cents after a ping from @franciscovg 

I don't see a case for varnishtop, because I think the Varnish Book should focus on learning and understanding Varnish.

What we currently cover (roughly):
- `varnishd`, `varnishlog`, `varnishstat`, `varnishadm`
- overall architecture
- HTTP specific headers
- VCL
- invalidation
- ESI

We already learn that varnish is more than just a caching process, and trained users should be able to look at the other tools by themselves. If the docs aren't enough, we should instead improve them. As for training, an appendix is entry for the other tools (my favourite being `varnishtest`=) feels enough.

**Comment by franciscovg** [comment]
``varnishtop`` is currently a section under the *Appendix B: Varnish Programs* chapter, and it is referenced in the *Varnish Distribution* and *Log Data Tools* sections. This seems to be sufficient.

Please reopen and comment on disagreement.
