### ISSUE TITLE
Cookie cleaning examples

### ISSUE THREAD

**Issue by KristianLyng** [varnish/Varnish-Book#7]
Perhaps a "practical VCL" bit? Or more exercises that does exactly this. cookie-removal is pretty common.

**Comment by franciscovg** [comment]
Closing this issue since the removal of ``Set-Cookie`` is handled in ``vcl_backend_response`` and the exercise https://www.varnish-software.com/book/master/chapters/VCL_Built_in_Subroutines.html#exercise-either-use-s-maxage-or-set-ttl-by-file-type shows how to remove ``Set-Cookie``.

Related links that support the closure of this issue:
https://www.varnish-software.com/book/master/chapters/VCL_Built_in_Subroutines.html#vcl-backend-response
https://www.varnish-software.com/book/master/chapters/VCL_Built_in_Subroutines.html#example-setting-ttl-of-jpg-urls-to-60-seconds

If somebody still think that another exercise is needed, please outline it and reopen this issue.
